config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :trips do
    resource  :booking, controller: 'trips/bookings', only: :create
  end

  resources :open_trips, only: :index

  resources :my_trips, only: :index
end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id                    :bigint           not null, primary key
#  destination           :text             default(""), not null
#  end_time              :datetime
#  is_recurring_schedule :boolean          default(FALSE), not null
#  last_booking_time     :datetime
#  maximum_person        :integer          default(1), not null
#  meeting_point         :text             default(""), not null
#  minimum_person        :integer          default(1), not null
#  start_time            :datetime
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :bigint           not null
#
# Indexes
#
#  index_trips_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Trip < ApplicationRecord
  has_many    :booked_trips

  belongs_to  :user

  validates  :start_time, :end_time, :user_id, :maximum_person,
             :minimum_person, :last_booking_time, :meeting_point,
             :destination, presence: true

  validates  :minimum_person, :maximum_person, numericality: { greater_than: 0 }
end

app/controllers/trips/bookings_controller.rb
class Trips::BookingsController < ApplicationController
  before_action :authenticate_user!

  def create
    booked_trip = BookedTrip.new(booking_params)
    if booked_trip.save!
      redirect_to root_path
    else
      render 'open_trips/index'
    end
  end

  private

  def booking_params
    params[:booked_trip] = {
      trip_id: params[:trip_id]
    }
    params.require(:booked_trip).permit(:trip_id).merge(
      user_id: current_user.id,
      payment_status_id: PaymentStatus.pending.id
    )
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
    authorize @trips
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
    authorize @trip
  end

  # GET /trips/1/edit
  def edit
    authorize @trip
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)
    authorize @trip

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    authorize @trip
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    authorize @trip
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(
        :start_time, :end_time, :minimum_person, :maximum_person,
        :last_booking_time, :is_recurring_schedule, :meeting_point, :destination
      ).merge(user_id: current_user.id)
    end
end

app/helpers/trips/bookings_helper.rb
module Trips::BookingsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :minimum_person %>
    <%= form.number_field :minimum_person %>
  </div>

  <div class="field">
    <%= form.label :maximum_person %>
    <%= form.number_field :maximum_person %>
  </div>

  <div class="field">
    <%= form.label :meeting_point %>
    <%= form.text_field :meeting_point %>
  </div>

  <div class="field">
    <%= form.label :last_booking_time %>
    <%= form.datetime_select :last_booking_time %>
  </div>

  <div class="field">
    <%= form.label :is_recurring_schedule %>
    <%= form.check_box :is_recurring_schedule %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Minimum person</th>
      <th>Maximum person</th>
      <th>Last booking time</th>
      <th>Is recurring schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.destination %></td>
        <td><%= trip.start_time %></td>
        <td><%= trip.end_time %></td>
        <td><%= trip.minimum_person %></td>
        <td><%= trip.maximum_person %></td>
        <td><%= trip.last_booking_time %></td>
        <td><%= trip.is_recurring_schedule %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @trip.destination %></h1>
</p>

<p>
  <strong>Start time:</strong>
  <%= @trip.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @trip.end_time %>
</p>

<p>
  <strong>Minimum person:</strong>
  <%= @trip.minimum_person %>
</p>

<p>
  <strong>Meeting point:</strong>
  <%= @trip.meeting_point %>
</p>

<p>
  <strong>Maximum person:</strong>
  <%= @trip.maximum_person %>
</p>

<p>
  <strong>Last booking time:</strong>
  <%= @trip.last_booking_time %>
</p>

<p>
  <strong>Is recurring schedule:</strong>
  <%= @trip.is_recurring_schedule %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>